Repository freeCodeCamp/learn, pull requests merged in 2018-06, with the labels that each got.

#142 fix(typo): Fixes typo the made the local completedChallenges array unuseable
  src/redux/app/index.js
Labels: UX, bug, critical path

#151 Feat: Donation integration
  gatsby-node.js
  package.json
  seed/challenges/05-apis-and-microservices/apis-and-microservices-projects.json
  seed/challenges/06-information-security-and-quality-assurance/quality-assurance-and-information-security-projects.json
  src/components/Donation/Donation.js
  src/components/Donation/components/CardForm.js
  src/components/Donation/components/DonateCompletion.js
  src/components/Donation/components/DonateForm.js
  src/components/Donation/components/StripeCardForm.js
  src/components/Donation/donation.css
  src/components/Donation/index.js
  src/components/Map/components/Block.js
  src/components/MapModal/index.js
  src/components/MapModal/map-modal.css
  src/html.js
  src/layouts/index.js
  src/pages/index.js
  src/redux/app/index.js
  src/templates/Challenges/project/Tool-Panel.js
  src/templates/Challenges/redux/completion-epic.js
  static/img/powered_by_stripe.svg
  yarn.lock
Labels: blocked

#145 Updated index.md
  src/introductions/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/index.md
Labels: status: blocked

#150 Add MathJax
  src/head/index.js
  src/head/mathjax.js
  src/templates/Challenges/components/Side-Panel.js
  src/templates/Challenges/components/side-panel.css
Labels: status: ready for QA

#169 fixing grammatical and spelling errors in javascript intro
  src/introductions/javascript-algorithms-and-data-structures/basic-javascript/index.md
Labels: status: ready for QA

#179 fix: add cats json for seeding challenges
  static/json/cats.json
Labels: status: ready for QA

#149 Add description
  src/introductions/javascript-algorithms-and-data-structures/basic-data-structures/index.md
Labels: status: ready for QA

#164 Fix navbar
  src/components/Header/header.css
Labels: status: ready for QA

#167 Fixed: Added styles for mobile
  src/components/Map/map.css
  src/pages/index.css
Labels: status: needs update

#111 WIP: decodeHTMLEntities
  src/templates/Challenges/classic/Show.js
  utils/decodeHTMLEntities.js
Labels: status: needs update

#183 Description for Basic Algorithm Scripting
  src/introductions/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md
Labels: status: ready for QA

#205 fix(editor): update night mode styles for the editor
  src/templates/Challenges/classic/Editor.js
Labels: status: ready for QA
